projects:
  server:
    schemaPath: src/prisma/schema.graphql
    extensions:
      endpoints:
        dev: http://172.21.138.57:5466
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/prisma/prisma.binding.ts