projects:
  server:
    schemaPath: src/prisma/schema.graphql
    extensions:
      endpoints:
        dev: http://127.0.0.1:4466
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/prisma/prisma.binding.ts
